<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php 
$helper = Mage::helper('venedor');
$show_attributes = $helper->getShowAttributes();
$active_filters = $this->getLayer()->getState()->getActiveFilters();
if ($active_filters) : 
foreach ($active_filters as $_filter) {
    if ($_filter->getType()=='catalog/layer_filter_attribute') {
        $show_attributes[] = $_filter->getAttributeModel()->getAttributeCode();
    }
}
endif;
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): 
                    $show_items = false;
                    if ($_filter->getType()!='catalog/layer_filter_attribute') {
                        $show_items = true;
                    } else {
                        continue;
                    }
                    if ($helper->showAllAttributes())
                        $show_items = true;
                ?>
                <?php if($_filter->getItemsCount()): ?>
                    <dt><?php echo $this->__($_filter->getName()) ?><a href="#" class="button-arrow<?php echo $show_items?' open':''; ?>"></a></dt>
                    <dd style="display:<?php echo $show_items?'block':'none' ?>;"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php foreach ($_filters as $_filter): 
                    $show_items = false;
                    if ($_filter->getType()=='catalog/layer_filter_attribute') {
                        $code = $_filter->getAttributeModel()->getAttributeCode();
                        if (in_array($code, $show_attributes))
                            $show_items = true;
                    } else {
                        continue;
                    }
                    if ($helper->showAllAttributes())
                        $show_items = true;
                ?>
                <?php if($_filter->getItemsCount()): ?>
                    <dt><?php echo $this->__($_filter->getName()) ?><a href="#" class="button-arrow<?php echo $show_items?' open':''; ?>"></a></dt>
                    <dd style="display:<?php echo $show_items?'block':'none' ?>;"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">
            //<![CDATA[
                decorateDataList('narrow-by-list');
                jQuery(function($) {
                    $('#narrow-by-list > dd > ol').each(function() {
                        var h = $(this).height();
                        if (h > 300) {
                            $(this).css('height', '300px');
                            $(this).jScrollPane({
                                autoReinitialise: true,
                                mouseWheelSpeed: 60
                            });
                        }                        
                    });
                    if ($('.block-layered-nav .button-arrow').length) {
                        $('.block-layered-nav .button-arrow').unbind('click').click(function(e) {
                            e.preventDefault();
                            $(this).parents('dt').next().stop().slideToggle();
                            if ($(this).hasClass('open'))
                                $(this).removeClass('open');
                            else
                                $(this).addClass('open');
                        });
                    }
                });
            //]]>
            </script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
