<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
echo $this->getDesignStyles();
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
$venedor = $this->helper('venedor');
$rowClass = $venedor->getRowClass();
$spanClass = $venedor->getSpanClass();
?>

<div class="page-title">
    <h1 class='h1_opc'><?php echo Mage::getStoreConfig('opc/global/title') ?></h1>
    <p class="desc"><?php echo $this->__('Fill in the Fields below to complete your purchase!')?></p>
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
    <p class="onepagecheckout_loginarea">
        <?php echo $this->getChildHtml('login');?>
    </p>
    <?php } ?>
</div>

<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">

    <div class="<?php echo $rowClass ?>">
        <div class="<?php echo $spanClass ?>6 opc-col-left">
            <form id="opc-address-form-billing" method="post">
                <?php echo $this->getChildHtml('billing')?>
            </form>

            <form id="opc-address-form-shipping" class="hidden" method="post">
            <?php echo $this->getChildHtml('shipping')?>
            </form>

        </div>

        <div class="<?php echo $spanClass ?>6 opc-col-center">
            <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
            <div class="shipping-block">
                <h3><?php echo $this->__('Shipping Method')?></h3>
                <div class="step">
                    <div id="shipping-block-methods">
                        <?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
                    </div>
                </div>
            </div>
            <?php endif;?>
            
            <?php if(Mage::helper('opc')->isShowDiscount()):?>
            <div class="discount-block">
                <h3><?php echo $this->__('Discount Codes')?></h3>
                <div class="step">
                    <?php echo $this->getChildhtml('coupon');?>
                </div>
            </div>
            <?php endif; ?>

            <?php if(Mage::helper('opc')->isShowComment()):?>
                <?php echo $this->getChildhtml('customer.comment');?>
            <?php endif;?>

	    <div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
                <h3><?php echo $this->__('Payment Method')?></h3>
                <div class="step">
                    <?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
                </div>
            </div>

            <?php if (Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
            <div class="signature-block">
                <h3><?php echo $this->__('Signature')?></h3>
                <div class="step collapse-block hidden">
                    <?php echo $this->getChildhtml('opcsignature');?>
                </div>
            </div>
            <?php endif;?>            

        </div>
    </div>

    <div class="opc-col-right">
        <h3><?php echo $this->__('Review Your Order')?></h3>
        <div class="step">
            <div class="order-review" id="opc-review-block">
            <?php echo $this->_getReviewHtml()?>
            </div>
        </div>
        <div class="opc-review-actions" id="checkout-review-submit">
            <?php echo $this->getChildHtml('agreements')?>
            <?php echo $this->getChildHtml('opc.newsletters');?>
            <button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button button-inverse btn-lg btn-large btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
        </div>
    </div>
</div>
<script>
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>