<?php
#####################################################################################################
#
#					Module pour la plateforme de paiement Systempay
#						Version : 1.2 (révision 46959)
#									########################
#					Développé pour Magento
#						Version : 1.5.1.0
#						Compatibilité plateforme : V2
#									########################
#					Développé par Lyra Network
#						http://www.lyra-network.com/
#						13/05/2013
#						Contact : supportvad@lyra-network.com
#
#####################################################################################################
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
<?php
	// Get selected values from module configuration
	$cards = $this->getConfigData('gift_cards'); 
	if (!empty($cards)) {
		$cards = explode(",", $cards);
		$html = '';
		
		if(count($cards) == 1) {
			// Show the unique card logo
			$html .= '<input type="hidden" id="systempay_gift_cc_type_'.$cards[0].'" value="'.$cards[0].'" name="payment[systempay_gift_cc_type]"/>' ;
			$html .= '<label style="float: none !important;" for="systempay_gift_cc_type_'.$cards[0].'">
						<img style="margin-right:10px; height:20px;" alt="'.$cards[0].'" src="'.$this->getGcTypeImageSrc($cards[0]).'" title="' . $this->getGcTypeLabel($cards[0]) . '" />
					  </label>';
		} else {
			// Show card logos as radio buttons
			for ($i = 0; $i < count($cards); $i++) {
				$html .= '<input type="radio" class="radio" id="systempay_gift_cc_type_'.$cards[$i].'"'.($i == 0 ? ' checked="checked"' : '').' value="'.$cards[$i].'" name="payment[systempay_gift_cc_type]"/>' ;
				$html .= '<label style="float: none !important;" for="systempay_gift_cc_type_'.$cards[$i].'">
							<img style="margin-right:10px; height:20px;" alt="'.$cards[$i].'" src="'.$this->getGcTypeImageSrc($cards[$i]).'" title="' . $this->getGcTypeLabel($cards[$i]) . '" />
						  </label>';
			}
		}
		
		echo '<li>' . $html . '</li>';
	}
?>

	<li><?php echo Mage::helper('systempay')->__('You will be redirected to the payment page after the order confirmation.') ?></li>
</ul>