<?php
#####################################################################################################
#
#					Module pour la plateforme de paiement Systempay
#						Version : 1.2 (révision 46959)
#									########################
#					Développé pour Magento
#						Version : 1.5.1.0
#						Compatibilité plateforme : V2
#									########################
#					Développé par Lyra Network
#						http://www.lyra-network.com/
#						13/05/2013
#						Contact : supportvad@lyra-network.com
#
#####################################################################################################
?>

<div class="v-middle" style="display: inline-block; width: 90%; background-color: #eee;">
	<span style="position: absolute; padding-top: 5px;"><?php echo $this->getMethodTitle()?>&nbsp;</span>
	<img class="v-middle" style="width: 100px; float: right;" src="<?php echo $this->escapeHtml($this->getLogoSrc())?>" alt="Systempay" >
</div>