<?php
/**
 * Miura Menu+ Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Miura
 * @package    Miura_MenuPlus
 * @author     Clement Larduinat
 * @copyright  Copyright (c) 2011 Miura Conseil (http://www.miura-conseil.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $_menu = $this->renderMenuHtml() ?>

<?php if ($_menu): ?>
    <div class="nav-container">
        <div id="mddm" class="<?php if ($this->getSkinClass()) echo $this->getSkinClass(); ?>">
            <?php echo $_menu ?>
            <div class="mddm-clear"></div>
        </div>
        <?php echo $this->getJs(); ?>
    </div>
<?php endif; ?>
