<div class="comment-block">
    <h3><?php echo $this->__('Comment')?></h3>
    <div class="step">
        <form autocomplete="off">
            <div class="discount">
                <div class="discount-form">
                    <div class="input-box">
                        <textarea class="input-text" id="customer_comment" name="customer_comment"></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>