<?php $items = $this->getItems() ?>
<div class="page-head">
<h3><?php echo $this->getHeader()?></h3>
</div>
<div class="content">
<?php if ($items): ?>
<?php $width = floor(100/count($items)) ?>
<?php foreach ($items as $letters): ?>
    <?php foreach ($letters as $letter => $options): ?>
        <ul class="bare-list">
            <?php foreach ($options as $o): ?>
                <li style="float:left">
                    <a href="<?php echo $o['url'] ?>"><?php echo $this->htmlEscape($o['label']) ?></a> <?php if ($this->getShowCounts()) { echo '('.$o['cnt'].')'; } ?>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>
<?php endforeach ?>
<?php endif ?>
</div>
