<?php
/**
 * 1997-2012 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to ecommerce@quadra-informatique.fr so we can send you a copy immediately.
 *
 *  @author Quadra Informatique <ecommerce@quadra-informatique.fr>
 *  @copyright 1997-2012 Quadra Informatique
 *  @version Release: $Revision: 2.0.6 $
 *  @license http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php $_code = $this->getMethodCode(); ?>
<fieldset class="form-list">
  	<?php $cards = $this->getCreditCardsAccepted(); ?>
  	<?php if($cards): ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
          	<div class="input-box">
              	<?php echo $this->__('Select your credit card') ?>
            </div>
        </li>
        <li>
      	<?php foreach($cards as $key => $value): ?>
            <input id="<?php echo $_code ?>_atos_cc_<?php echo $key ?>" class="atos_cc validate-one-required" type="radio" name="payment[cc_type]" value="<?php echo $key ?>" />
            <a href="javascript:;" onclick="document.getElementById('<?php echo $_code ?>_atos_cc_<?php echo $key ?>').checked=true;"><img style="vertical-align:middle;" src="<?php echo $this->getSkinUrl('images/media/atos/') . $key ?>.gif" alt="<?php echo $value ?>" /></a>
            <label style="float: none;" for="<?php echo $_code ?>_atos_cc_<?php echo $key ?>"><?php echo $value ?></label>
            <div style="margin-bottom:6px;"></div>
      	<?php endforeach; ?>
      	</li>
    </ul>
    <?php endif; ?>
</fieldset>
